############################################################
## Send notification when doorbell is triggered           ##
############################################################

- alias: Notify when doorbell is pressed
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_button
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.automation_override
      state: 'off'
  action:
    - service: counter.increment
      entity_id: counter.doorbell_button_pressed_counter
    - service: counter.increment
      entity_id: counter.doorbell_button_pressed_total
    - service: script.turn_on
      entity_id: script.doorbell_is_triggered


- alias: Notify when doorbell is pressed for 20 seconds
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_button
      to: "on"
      for:
        seconds: 20
  condition:
    - condition: state
      entity_id: input_boolean.automation_override
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.doorbell_is_triggered_long


- alias: Notify when doorbell is jammed
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_button
      to: "on"
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: input_boolean.automation_override
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.doorbell_is_jammed


- alias: Reset doorbell counter when idle for 1 minute
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_button
      to: "off"
      for:
        minutes: 1
  action:
    - service: counter.reset
      entity_id: counter.doorbell_button_pressed_counter


############################################################
## Enable disable doorbell button                         ##
############################################################

- alias: Adjust doorbell enabled setting when input changes
  trigger:
    platform: state
    entity_id: input_boolean.doorbell_button_enabled
  action:
    - service: mqtt.publish
      data:
        topic: "home/doorbell/ring/set"
        retain: false
        payload_template: >
          {% if is_state('input_boolean.doorbell_button_enabled', 'on') %}
            {"button_disabled":0}
          {% else %}
            {"button_disabled":1}
          {% endif %}


- alias: Adjust doorbell switch when sensor changes
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button_enabled
  action:
    - service_template: >
        {%- if is_state('binary_sensor.doorbell_button_enabled', 'on') %}
            input_boolean.turn_on
        {%- else %}
            input_boolean.turn_off
        {%- endif %}
      data:
        entity_id: input_boolean.doorbell_button_enabled
