---
- platform: mqtt
  name: Doorbell Button
  state_topic: "home/doorbell/button"
  icon: mdi:bell
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: Doorbell Button Disabled
  state_topic: "home/doorbell/ring"
  value_template: "{{ value_json.button_disabled }}"
  icon: mdi:bell
  payload_off: 1
  payload_on: 0

