- platform: mqtt
  name: Doorbell Button
  state_topic: "home/doorbell/button"
  payload_on: "ON"
  payload_off: "OFF"
  icon: mdi:bell

- platform: mqtt
  name: Doorbell Button Enabled
  state_topic: "home/doorbell/ring"
  payload_off: 1
  payload_on: 0
  value_template: "{{ value_json.button_disabled }}"
  icon: mdi:bell
